### ISSUE TITLE
Missing some things

### ISSUE THREAD

**Issue by westor7** [mIRC-Scripters/mSL-VSCode-Extension#15]
Have a look at these .mrc files it seems some things are not coloring correctly.

1. https://github.com/DukeLupus/dlFilter/blob/master/dlFilter.mrc
2. https://github.com/independentcod/psyBNC-Win/blob/master/defaults/scripts/psyBNC.mrc#L2-L13

- Thanks!

**Comment by Kedyn** [comment]
The first link, brings out a few minor and big issues.
1. A problem with events using variables.
2. Well known issue with the **$&** identifier. (big issue)
3. A problem with the single line comment **;** and brackets **{** and **}**.

The second link, has to do with a missing **)** on an **$iif(**, but if the script still works with said issue, we might have to look into it.

Although this currently affects both the highlighting here on GitHub and on VSCode, I believe this issue should be moved to only the [highlighting here on GitHub repo](https://github.com/Kedyn/language-msl) because I still have planned to move away from regex (textmate) highlighting system for the extension in favor of semantic highlighting. 

I do not have plans as to when I will start working on this, so for now I will keep this issue here, and will soon start fixing some of the minor bugs as soon as I can.

**Comment by westor7** [comment]
I thought https://github.com/Kedyn/language-msl was using this project stuff, so changes on this effecting the other.

**Comment by Kedyn** [comment]
Yes, that was the case, and in some way still is, but because this project will no longer be using regex. I think it would be best to keep them as separate things. I mean we could keep it as is, VSCode allows to have both and will prefer semantic highlighting over the textmate (regex). That being said, now I am thinking it wouldn't hurt to keep it as is, but maybe one will have issues that the other will not. What do you think?

**Comment by westor7** [comment]
I prefer to fix that on github side and then you can decide, because personally i think its more important to be correct on github that are hosted the most of the mSL codes, i think everything else needs to copy the github highlight to use in any other program/app but githubs syntax highlighting on mSL needs to be correct and up-to-date.

Ofc i can help you with that anytime :D

**Comment by Kedyn** [comment]
Agree, I have changed the readme on the https://github.com/Kedyn/language-msl repo. If you can contribute anything I will accept your pull request there. I will keep this issue open sense it is part of this project too.

**Comment by westor7** [comment]
Moved to #19
