### ISSUE TITLE
(How to)? evaluate the =$nick identifier

### ISSUE THREAD

**Issue by acvxqs** [mIRC-Scripters/mSL-VSCode-Extension#5]
`=$nick` is a special identifier. Inside the on chat and on serv events, if you want to send a message to the dcc chat/serv window rather than to send a message as a private message on IRC, you have to prefix the nickname with the equal sign '='. For convenience `=$nick` can be used as a shortcut for `= $+ $nick`, where `$nick` is evaluated properly.

Link: https://en.wikichip.org/wiki/mirc/identifiers/%3D$nick

**Comment by acvxqs** [comment]
I see you've already included it into the test file:

https://github.com/mIRC-Scripters/mSL-VSCode-Extension/blob/d45336864d391d1725792c3a2be5910ea01c7a3c/syntaxes/test/events.mrc#L174

**Comment by Kedyn** [comment]
Closed in [61fbf38](https://github.com/mIRC-Scripters/mSL-VSCode-Extension/commit/61fbf38fc2342aa1ef275c9501c79726a792fbfd)

Note: Cannot be added as part of only chat event because it might be part of parameters of a command or identifier, so it would be inside the scope of one of those. This must be checked on diagnostics.
